// tslint:disable
/**
 * Tags Service
 * Tags Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TagDto
 */
export interface TagDto {
    /**
     * @type {string}
     * @memberof TagDto
     */
    _id: string;
    /**
     * @type {string}
     * @memberof TagDto
     */
    readonly createdAt?: string;
    /**
     * @type {string}
     * @memberof TagDto
     */
    readonly updatedDate?: string;
    /**
     * tags
     * @type {TagDto}
     * @memberof TagDto
     */
    tags: TagDto;
}
