// tslint:disable
/**
 * Media Service
 * Media Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TagKeyValue,
} from './';

/**
 * @export
 * @interface MediaShareItemDto
 */
export interface MediaShareItemDto {
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    _id: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    readonly createdAt?: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    readonly updatedDate?: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    key: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    userId: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    title: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    summary?: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    description: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    uri: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    imageSrc?: string;
    /**
     * @type {boolean}
     * @memberof MediaShareItemDto
     */
    isPlayable?: boolean;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    visibility: MediaShareItemDtoVisibilityEnum;
    /**
     * @type {Array<TagKeyValue>}
     * @memberof MediaShareItemDto
     */
    tags?: Array<TagKeyValue> | null;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    eTag?: string;
    /**
     * @type {number}
     * @memberof MediaShareItemDto
     */
    shareCount: number;
    /**
     * @type {number}
     * @memberof MediaShareItemDto
     */
    viewCount: number;
    /**
     * @type {number}
     * @memberof MediaShareItemDto
     */
    likesCount: number;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    shareId: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    mediaItemId: string;
    /**
     * @type {string}
     * @memberof MediaShareItemDto
     */
    playlistId: string;
}

/**
 * @export
 * @enum {string}
 */
export enum MediaShareItemDtoVisibilityEnum {
    Private = 'private',
    Shared = 'shared',
    Subscription = 'subscription',
    Public = 'public'
}

