// tslint:disable
/**
 * Media Service
 * Media Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PlaylistShareItemDto
 */
export interface PlaylistShareItemDto {
    /**
     * @type {string}
     * @memberof PlaylistShareItemDto
     */
    _id: string;
    /**
     * @type {string}
     * @memberof PlaylistShareItemDto
     */
    readonly createdAt?: string;
    /**
     * @type {string}
     * @memberof PlaylistShareItemDto
     */
    readonly updatedDate?: string;
    /**
     * @type {string}
     * @memberof PlaylistShareItemDto
     */
    shareId: string;
    /**
     * @type {string}
     * @memberof PlaylistShareItemDto
     */
    mediaId: string;
    /**
     * @type {string}
     * @memberof PlaylistShareItemDto
     */
    playlistId: string;
}
