// tslint:disable
/**
 * Media Service
 * Media Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TagKeyValue
 */
export interface TagKeyValue {
    /**
     * @type {string}
     * @memberof TagKeyValue
     */
    key: string;
    /**
     * @type {string}
     * @memberof TagKeyValue
     */
    value: string;
}
