// tslint:disable
/**
 * Media Service
 * Media Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    PlaylistItemDto,
    PlaylistVisibilityType,
    TagKeyValue,
} from './';

/**
 * @export
 * @interface UpdatePlaylistDto
 */
export interface UpdatePlaylistDto {
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    _id: string;
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    readonly createdAt?: string;
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    readonly updatedDate?: string;
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    cloneOf?: string;
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    title: string;
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    description: string;
    /**
     * @type {string}
     * @memberof UpdatePlaylistDto
     */
    imageSrc: string;
    /**
     * @type {PlaylistVisibilityType}
     * @memberof UpdatePlaylistDto
     */
    visibility: PlaylistVisibilityType;
    /**
     * @type {Array<TagKeyValue>}
     * @memberof UpdatePlaylistDto
     */
    tags?: Array<TagKeyValue> | null;
    /**
     * @type {Array<string>}
     * @memberof UpdatePlaylistDto
     */
    mediaIds: Array<string>;
    /**
     * @type {Array<PlaylistItemDto>}
     * @memberof UpdatePlaylistDto
     */
    playlistItems: Array<PlaylistItemDto>;
}
