// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, OperationOpts, RawAjaxResponse } from '../runtime';

/**
 * no description
 */
export class WellKnownApi extends BaseAPI {

    /**
     */
    wellKnownControllerAasa(): Observable<void>
    wellKnownControllerAasa(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    wellKnownControllerAasa(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        return this.request<void>({
            url: '/.well-known/apple-app-site-association',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
