// tslint:disable
/**
 * User Service
 * User Service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpQuery, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';

export interface EmailControllerSendEmailRequest {
    userId: string;
    email: string;
}

/**
 * no description
 */
export class EmailApi extends BaseAPI {

    /**
     */
    emailControllerSendEmail({ userId, email }: EmailControllerSendEmailRequest): Observable<void>
    emailControllerSendEmail({ userId, email }: EmailControllerSendEmailRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    emailControllerSendEmail({ userId, email }: EmailControllerSendEmailRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(userId, 'userId', 'emailControllerSendEmail');
        throwIfNullOrUndefined(email, 'email', 'emailControllerSendEmail');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'userId': userId,
            'email': email,
        };

        return this.request<void>({
            url: '/api/email/send-email',
            method: 'POST',
            query,
        }, opts?.responseOpts);
    };

}
