// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MediaVisibilityType,
    TagKeyValue,
} from './';

/**
 * @export
 * @interface CreateMediaItemDto
 */
export interface CreateMediaItemDto {
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    title: string;
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    summary: string;
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    description: string;
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    uri: string;
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    imageSrc: string;
    /**
     * @type {boolean}
     * @memberof CreateMediaItemDto
     */
    isPlayable?: boolean;
    /**
     * @type {MediaVisibilityType}
     * @memberof CreateMediaItemDto
     */
    visibility: MediaVisibilityType;
    /**
     * @type {Array<TagKeyValue>}
     * @memberof CreateMediaItemDto
     */
    tags?: Array<TagKeyValue> | null;
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    key: string;
    /**
     * @type {string}
     * @memberof CreateMediaItemDto
     */
    eTag: string;
}
