// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MediaShareItemResponseDto,
    PlaylistShareItemResponseDto,
} from './';

/**
 * @export
 * @interface ShareItemsResponseDto
 */
export interface ShareItemsResponseDto {
    /**
     * @type {MediaShareItemResponseDto}
     * @memberof ShareItemsResponseDto
     */
    mediaItems: MediaShareItemResponseDto;
    /**
     * @type {PlaylistShareItemResponseDto}
     * @memberof ShareItemsResponseDto
     */
    playlists: PlaylistShareItemResponseDto;
}
