// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';

export interface ActionsControllerOpenInAppRequest {
    userId: string;
}

/**
 * no description
 */
export class ActionsApi extends BaseAPI {

    /**
     */
    actionsControllerOpenInApp({ userId }: ActionsControllerOpenInAppRequest): Observable<void>
    actionsControllerOpenInApp({ userId }: ActionsControllerOpenInAppRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    actionsControllerOpenInApp({ userId }: ActionsControllerOpenInAppRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(userId, 'userId', 'actionsControllerOpenInApp');

        return this.request<void>({
            url: '/api/actions/open-invitation/{userId}'.replace('{userId}', encodeURI(userId)),
            method: 'GET',
        }, opts?.responseOpts);
    };

}
